jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # 필요한 Node.js 버전

    - name: Install Node.js dependencies
      run: npm install

    - name: Set up Dart
      uses: subosito/dart-action@v2
      with:
        dart-version: 'stable'

    - name: Install Dart dependencies
      run: dart pub get

    - name: Create .env file
      run: echo "OPEN_API_KEY=${{ secrets.OPEN_AI_API_KEY }}" > .env

    - name: Generate env.g.dart
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Build project
      run: dart compile exe bin/main.dart -o build/my_project_executable

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
