name: oslar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dart_openai: ^5.1.0
  envied: ^0.5.4+1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
  - assets/config/.env #assets/.env
  - assets/images/logo.png