name: oslar
description: "Chat based on ChatGPT"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
    
  flutter_dotenv: ^5.1.0
  envied: ^0.5.4+1
  intl: ^0.19.0

  cupertino_icons: ^1.0.0
  dart_openai: ^5.1.0

  http: ^1.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
  - assets/config/.env
  - assets/images/logo.png
  - assets/images/oslar.png
  - assets/images/favicon.png