name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Install Dependencies
      run: flutter pub get

    - name: Create .env file
      run: echo "OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}" >> .env

    - name: Debug! Check for .env
      run: |
        echo "Checking for .env"
        ls -l .env
        cat .env

    - name: Build Web
      run: flutter build web --release

    - name: Update base href and mobile-web-app-capable meta tag
      run: |
        sed -i 's|<base href=".*">|<base href="/Oslar/">|g' build/web/index.html
        if ! grep -q 'meta name="mobile-web-app-capable"' build/web/index.html; then
          sed -i 's|</head>|<meta name="mobile-web-app-capable" content="yes">\n</head>|g' build/web/index.html
        fi

    - name: Add .nojekyll
      run: echo > build/web/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.STATIC_DEPLOY_KEY }}
        publish_dir: build/web
        publish_branch: gh-pages
