name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3' #flutter --version

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Node.js Server
      run: |
        npm install
        node api/getApiKey.js & 
        sleep 5

    - name: Create config directory if not exists
      run: mkdir -p assets/config

    - name: Create .env file with dummy data
      run: echo "OPEN_AI_API_KEY='dummy_data'" > assets/config/.env

    - name: Build Web
      run: flutter build web --release

    - name: Change favicon
      run: |
          mv build/web/favicon.png assets/images/favicon.png

    - name: Update base href and mobile-web-app-capable meta tag
      run: |
        sed -i 's|<base href=".*">|<base href="/Oslar/">|g' build/web/index.html
        if ! grep -q 'meta name="mobile-web-app-capable"' build/web/index.html; then
          sed -i 's|</head>|<meta name="mobile-web-app-capable" content="yes">\n</head>|g' build/web/index.html
        fi

    - name: Add .nojekyll
      run: echo > build/web/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.STATIC_DEPLOY_KEY }}
        publish_dir: build/web
        publish_branch: gh-pages
